stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.9-slim
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests

deploy:
  stage: deploy
  image: python:3.9-slim
  before_script:
    - apt-get update && apt-get install -y openssh-client
  script:
    - echo "Deploying to production server!"
    - pwd
    - ls -la 
    - mkdir -p /home/alex/Laba_3/deploy
    - cd ..
    - cp -r laba_3/* /home/alex/Laba_3/deploy
    - ls -la /home/alex/Laba_3/deploy
  artifacts:
    paths:
      - /builds/flyer6662640/laba_3
  only:
    - main
